spring:
  shardingsphere:
    datasource:
      names: db0,db1
      db0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/db_0?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
        username: root
        password: 123456
      db1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/db_1?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
        username: root
        password: 123456
    sharding:
      default-database-strategy:
        inline:
          sharding-column: user_id
          algorithm-expression: db$->{user_id%2}
      tables:
        user:
          actual-data-nodes: db$->{0..1}.user_$->{0..1}
          database-strategy:
            inline:
              sharding-column: id
              algorithm-expression: db$->{id%2}
          table-strategy:
            inline:
              sharding-column: id
              algorithm-expression: user_$->{id%2}
        person:
          actual-data-nodes: db$->{0..1}.person_$->{0..1}
          database-strategy:
            hint:
              algorithm-class-name: com.example.demo.config.CustomHintShardingStrategy
          table-strategy:
            hint:
              algorithm-class-name: com.example.demo.config.CustomHintShardingStrategy
    props:
      sql:
        show: true

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.example.demo.pojo
  type-enums-package: com.example.demo.myenum